name: reveal secret

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Base64 Encode Secret
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: |
          echo "Encoded value:"
          echo "$EMAIL_APP_PASSWORD" | base64
